package com.serasiautoraya.slimobiledrivertracking.MVP.JourneyOrder.Activity;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import com.serasiautoraya.slimobiledrivertracking.MVP.BaseModel.Model;

/**
 * Created by Randi Dwi Nandra on 24/03/2017.
 */

public class ActivityDetailResponseModel extends Model {

    @SerializedName("AssignmentId")
    @Expose
    private Integer AssignmentId;

    @SerializedName("JourneyActivityId")
    @Expose
    private Integer JourneyActivityId;

    @SerializedName("ActivityName")
    @Expose
    private String ActivityName;

    @SerializedName("AcitivityType")
    @Expose
    private String AcitivityType;

    @SerializedName("IsPhoto")
    @Expose
    private String IsPhoto;

    @SerializedName("TimeTarget")
    @Expose
    private String TimeTarget;

    @SerializedName("TimeBaseline")
    @Expose
    private String TimeBaseline;

    @SerializedName("TimeActual")
    @Expose
    private String TimeActual;

    @SerializedName("LocationTargetLat")
    @Expose
    private String LocationTargetLat;

    @SerializedName("LocationTargetLng")
    @Expose
    private String LocationTargetLng;

    @SerializedName("LocationTargetText")
    @Expose
    private String LocationTargetText;

    @SerializedName("IsSignature")
    @Expose
    private String IsSignature;

    @SerializedName("IsCodeVerification")
    @Expose
    private String IsCodeVerification;

    @SerializedName("CodeVerification")
    @Expose
    private String CodeVerification;

    @SerializedName("CargoType")
    @Expose
    private String[] CargoType;

    @SerializedName("UnitModel")
    @Expose
    private String UnitModel;

    @SerializedName("UnitNumber")
    @Expose
    private String UnitNumber;

    @SerializedName("NextActivity")
    @Expose
    private Integer NextActivity;

    @SerializedName("NextActivityLocationLat")
    @Expose

    private String NextActivityLocationLat;

    @SerializedName("NextActivityLocationLng")
    @Expose
    private String NextActivityLocationLng;

    @SerializedName("NextActivityLocationText")
    @Expose
    private String NextActivityLocationText;

    @SerializedName("TimezoneTimeTarget")
    @Expose
    private Integer TimezoneTimeTarget;

    @SerializedName("TimezoneNextActivityTimeTarget")
    @Expose
    private Integer TimezoneNextActivityTimeTarget;

    @SerializedName("NextActivityTimeTarget")
    @Expose
    private String NextActivityTimeTarget;

    @SerializedName("IsPOD")
    @Expose
    private String IsPOD;

    @SerializedName("PODGuide")
    @Expose
    private String PODGuide;

    /*
    * TODO delete this constructor, must not be created but generated by GSON from API
    * */

    public ActivityDetailResponseModel(Integer assignmentId, Integer journeyActivityId, String activityName, String acitivityType, String isPhoto, String timeTarget, String timeBaseline, String timeActual, String locationTargetLat, String locationTargetLng, String locationTargetText, String isSignature, String isCodeVerification, String codeVerification, String[] cargoType, String unitModel, String unitNumber, Integer nextActivity, String nextActivityLocationLat, String nextActivityLocationLng, String nextActivityLocationText, Integer timezoneTimeTarget, Integer timezoneNextActivityTimeTarget, String nextActivityTimeTarget, String isPOD, String PODGuide) {
        AssignmentId = assignmentId;
        JourneyActivityId = journeyActivityId;
        ActivityName = activityName;
        AcitivityType = acitivityType;
        IsPhoto = isPhoto;
        TimeTarget = timeTarget;
        TimeBaseline = timeBaseline;
        TimeActual = timeActual;
        LocationTargetLat = locationTargetLat;
        LocationTargetLng = locationTargetLng;
        LocationTargetText = locationTargetText;
        IsSignature = isSignature;
        IsCodeVerification = isCodeVerification;
        CodeVerification = codeVerification;
        CargoType = cargoType;
        UnitModel = unitModel;
        UnitNumber = unitNumber;
        NextActivity = nextActivity;
        NextActivityLocationLat = nextActivityLocationLat;
        NextActivityLocationLng = nextActivityLocationLng;
        NextActivityLocationText = nextActivityLocationText;
        TimezoneTimeTarget = timezoneTimeTarget;
        TimezoneNextActivityTimeTarget = timezoneNextActivityTimeTarget;
        NextActivityTimeTarget = nextActivityTimeTarget;
        IsPOD = isPOD;
        this.PODGuide = PODGuide;
    }

    public Integer getAssignmentId() {
        return AssignmentId;
    }

    public Integer getJourneyActivityId() {
        return JourneyActivityId;
    }

    public String getActivityName() {
        return ActivityName;
    }

    public String getAcitivityType() {
        return AcitivityType;
    }

    public String getIsPhoto() {
        return IsPhoto;
    }

    public String getTimeTarget() {
        return TimeTarget;
    }

    public String getTimeBaseline() {
        return TimeBaseline;
    }

    public String getTimeActual() {
        return TimeActual;
    }

    public String getLocationTargetLat() {
        return LocationTargetLat;
    }

    public String getLocationTargetLng() {
        return LocationTargetLng;
    }

    public String getLocationTargetText() {
        return LocationTargetText;
    }

    public String getIsSignature() {
        return IsSignature;
    }

    public String getIsCodeVerification() {
        return IsCodeVerification;
    }

    public String getCodeVerification() {
        return CodeVerification;
    }

    public String[] getCargoType() {
        return CargoType;
    }

    public String getUnitModel() {
        return UnitModel;
    }

    public String getUnitNumber() {
        return UnitNumber;
    }

    public Integer getNextActivity() {
        return NextActivity;
    }

    public String getNextActivityLocationLat() {
        return NextActivityLocationLat;
    }

    public String getNextActivityLocationLng() {
        return NextActivityLocationLng;
    }

    public String getNextActivityLocationText() {
        return NextActivityLocationText;
    }

    public Integer getTimezoneTimeTarget() {
        return TimezoneTimeTarget;
    }

    public Integer getTimezoneNextActivityTimeTarget() {
        return TimezoneNextActivityTimeTarget;
    }

    public String getNextActivityTimeTarget() {
        return NextActivityTimeTarget;
    }

    public String getIsPOD() {
        return IsPOD;
    }

    public String getPODGuide() {
        return PODGuide;
    }
}
